# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/Nexys-A7-100T-Master.xdc

# IP: ip/ddr/ddr.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr || ORIG_REF_NAME==ddr} -quiet] -quiet

# XDC: c:/Users/Katie/Downloads/Nexys-A7-OOB-hw.xpr/hw/hw.gen/sources_1/ip/ddr/ddr/user_design/constraints/ddr.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr || ORIG_REF_NAME==ddr} -quiet] -quiet

# XDC: c:/Users/Katie/Downloads/Nexys-A7-OOB-hw.xpr/hw/hw.gen/sources_1/ip/ddr/ddr/user_design/constraints/ddr_ooc.xdc
